### ISSUE TITLE
cmdline customization

### ISSUE THREAD

**Issue by ybtag** [cfig/Android_boot_image_editor#121]
Any way to customize the kernel command line? It just copies the command line of the unmodified image.

**Comment by cfig** [comment]
#### 1. If your kernel cmdline is in boot.img, you can unpack boot.img and modify build/unzip_boot/boot.json, 
```
{
  "info" : {
    "output" : "boot.img",
    "json" : "boot.json",
    "headerVersion" : 4,
    "headerSize" : 1584,
    "pageSize" : 4096,
    "cmdline" : "xx=yy",
    "osVersion" : "12.0.0",
    "osPatchLevel" : "2021-10-00",
    "imageSize" : 33554432,
    "signatureSize" : 4096
  },

```

#### 2. If your kernel cmdline is in vendor_boot.img, please unpack vendor_boot.img and modify like this:
build/unzip_boot/vendor_boot.json
```
{
  "info" : {
    "output" : "vendor_boot.img",
    "json" : "vendor_boot.json",
    "headerVersion" : 4,
    "product" : "",
    "headerSize" : 2128,
    "pageSize" : 2048,
    "cmdline" : "earlycon=exynos4210,0x10A00000 console=ttySAC0,115200 androidboot.console=ttySAC0 printk.devkmsg=on at24.write_timeout=100 buildvariant=userdebug log_buf_len=1024K bootconfig",
    "tagsLoadAddr" : 268435712,
    "kernelLoadAddr" : 268468224,
    "imageSize" : 28518400
  },

```

**Comment by cfig** [comment]
If it doesn't work for you, please describe your detailed steps and upload the images. 
Another possibility is that some customized bootloader may ignore the kernel commandline part of some images.

**Comment by ybtag** [comment]
Thanks. I guess my bootloader is one of those 😦.

**Comment by cfig** [comment]
If you can get the "/proc/cmdline" of the running system, that would be good enough to go on.
Normally bootloader will combine internal cmdline and the values from some Android images, like boot.img, vendor_boot.img, vendor_kernel_boot.img or init_boot.img, you can try to identify which images the final cmdline come from, then you can modify that image, and you can customize it .....

**Comment by Saikatsaha1996** [comment]
> If you can get the "/proc/cmdline" of the running system, that would be good enough to go on. Normally bootloader will combine internal cmdline and the values from some Android images, like boot.img, vendor_boot.img, vendor_kernel_boot.img or init_boot.img, you can try to identify which images the final cmdline come from, then you can modify that image, and you can customize it .....

@cfig Hello sorry for ping.. ! I don't have any issues thats Why i don't want to create issues.. but i want help.. thats Why asking here.. can you help me with Vendor_boot ? Actually i am working on mainline kernel .. but my device bootloader is OnePlus bootloader.. and it's very horrible.. for bootloader i have to create custom empty dtbo.. and i successfully created.. but i don't know how to create vendor_boot.. my headr version 3 so boot.img not appended .. vendor boot is appended.. and i have my mainline dtb.. i was tried with erase dtbo & vendor boot but device directly came back to bootloader.. so after flash custom empty dtbo partition device not came back to bootloader but device rebooting randomly.. so i guess kernel not loading.. because i have to create valide vendor_boot also .. and which i don't know.. can you help please ?

**Comment by Rofikkernel** [comment]
@Saikatsaha1996  what device you want to port to mainline

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 what device you want to port to mainline

Already successfully added framebuffer .. have issues with secure pincontrol vendor_boot no more required.. only empty dtbo is enough..
