### ISSUE TITLE
Cannot unpack this image

### ISSUE THREAD

**Issue by yuanpeterli** [cfig/Android_boot_image_editor#34]
When unpacking the attached twrp recovery image, the kernel size is 0.
(Unzip the file first to extract recovery.img)
[twrp-3.3.1.img.zip](https://github.com/cfig/Android_boot_image_editor/files/3877145/twrp-3.3.1.img.zip)

**Comment by cfig** [comment]
Hi,
This image seems to have some customization in packing format,
let me have a check\

**Comment by cfig** [comment]
```
000001f0: dcc1 d54b 6d69 6372 6f6c 6f61 6465 7220  ...Kmicroloader 
00000200: 6279 2078 797a 2e20 436f 7079 7269 6768  by xyz. Copyrigh
00000210: 7420 3230 3139 2e00 4a75 6d70 2074 6f20  t 2019..Jump to 
00000220: 7468 6520 7061 796c 6f61 6400 536f 6d65  the payload.Some
00000230: 7468 696e 6720 7765 6e74 2068 6f72 7269  thing went horri
00000240: 626c 7920 7772 6f6e 6721 0000 99ec d14b  bly wrong!.....K
00000250: 904c d24b 0000 0000 0000 0000 0000 0000  .L.K............
00000260: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```
From the file header, the image is generated with tools from below link:
https://github.com/xyzz/amonet
The packing/loading process is also open sourced there. Hope this info helps.

Since I don't have the device to run and verify the ROM, I am not motivated to add support for this image. But if you can work out a way to do the unpacking and packing and share it, that will be grateful.

Thanks.

**Comment by cfig** [comment]
I checked latest twrp for Pixel 3(blueline) + Android 10, it doesn't work.
And according to some twitter posts, there is problem for TWRP to support latest Android recovery.
